use crate::config::{normalize_path, Account, Manifest, ShellIntegration};
use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;

pub struct Generator {
    base_dir: PathBuf,
}

pub struct GenerationResult {
    pub git_includes_path: PathBuf,
    pub ssh_config_path: PathBuf,
    pub generated_files: Vec<PathBuf>,
}

impl Generator {
    pub fn new(base_dir: PathBuf) -> Self {
        Self { base_dir }
    }

    pub fn default_base_dir() -> PathBuf {
        if let Some(config_dir) = dirs::config_dir() {
            config_dir.join("gh-multiaccount")
        } else if let Some(home) = dirs::home_dir() {
            home.join(".config").join("gh-multiaccount")
        } else {
            PathBuf::from(".config/gh-multiaccount")
        }
    }

    pub fn apply(&self, manifest: &Manifest) -> Result<GenerationResult> {
        let mut generated_files = Vec::new();

        let git_dir = self.base_dir.join("git");
        let ssh_dir = self.base_dir.join("ssh");
        let shell_dir = self.base_dir.join("shell");

        fs::create_dir_all(&git_dir).context("Failed to create git config directory")?;
        fs::create_dir_all(&ssh_dir).context("Failed to create ssh config directory")?;

        let mut includes_content =
            String::from("# Generated by git-account-switcher. DO NOT EDIT.\n");
        let mut sorted_accounts: Vec<(&String, &Account)> = manifest.accounts.iter().collect();
        sorted_accounts.sort_by_key(|(id, _)| *id);

        for (account_id, account) in &sorted_accounts {
            let account_gitconfig_path = git_dir.join(format!("{}.gitconfig", account_id));
            let account_gitconfig_content = self.generate_account_gitconfig(account_id, account);
            fs::write(&account_gitconfig_path, account_gitconfig_content)
                .with_context(|| format!("Failed to write {}", account_gitconfig_path.display()))?;
            generated_files.push(account_gitconfig_path.clone());

            for root in &account.roots {
                let norm = normalize_path(root);
                let root_str = norm.to_string_lossy();
                let trailing_slash_root = if root_str.ends_with('/') {
                    root_str.to_string()
                } else {
                    format!("{}/", root_str)
                };

                includes_content.push_str(&format!(
                    "[includeIf \"gitdir/i:{}\"]\n    path = {}\n",
                    trailing_slash_root,
                    account_gitconfig_path.display()
                ));

                if manifest.settings.shell_integration == ShellIntegration::Direnv {
                    let envrc_path = norm.join(".envrc");
                    if norm.exists() {
                        let envrc_content = "# .envrc - generated by git-account-switcher. DO NOT EDIT.\neval \"$(git-account-switcher env --shell bash)\"\n";
                        fs::write(&envrc_path, envrc_content)
                            .with_context(|| format!("Failed to write {}", envrc_path.display()))?;
                        generated_files.push(envrc_path);
                    }
                }
            }
        }

        let includes_path = git_dir.join("includes.gitconfig");
        fs::write(&includes_path, includes_content)
            .with_context(|| format!("Failed to write {}", includes_path.display()))?;
        generated_files.push(includes_path.clone());

        let ssh_config_path = ssh_dir.join("config");
        let ssh_content = self.generate_ssh_config(&sorted_accounts);
        fs::write(&ssh_config_path, ssh_content)
            .with_context(|| format!("Failed to write {}", ssh_config_path.display()))?;
        generated_files.push(ssh_config_path.clone());

        if manifest.settings.shell_integration == ShellIntegration::Wrapper {
            fs::create_dir_all(&shell_dir).context("Failed to create shell config directory")?;
            let wrapper_path = shell_dir.join("wrapper.zsh");
            let wrapper_content = self.generate_shell_wrapper();
            fs::write(&wrapper_path, wrapper_content)
                .with_context(|| format!("Failed to write {}", wrapper_path.display()))?;
            generated_files.push(wrapper_path);
        }

        Ok(GenerationResult {
            git_includes_path: includes_path,
            ssh_config_path,
            generated_files,
        })
    }

    fn generate_account_gitconfig(&self, account_id: &str, account: &Account) -> String {
        let mut s = String::new();
        s.push_str("# Generated by git-account-switcher. DO NOT EDIT.\n");
        s.push_str("[user]\n");
        s.push_str(&format!("    name = {}\n", account.name));
        s.push_str(&format!("    email = {}\n", account.email));

        if let Some(signing_key) = &account.signing_key {
            s.push_str(&format!("    signingkey = {}\n", signing_key));
            s.push_str("[commit]\n");
            s.push_str("    gpgsign = true\n");
        }

        s.push_str("[ghmultiaccount]\n");
        s.push_str(&format!("    account = {}\n", account_id));
        s.push_str("[github]\n");
        s.push_str(&format!("    account = {}\n", account_id));

        s
    }

    fn generate_ssh_config(&self, accounts: &[(&String, &Account)]) -> String {
        let mut s = String::new();
        s.push_str("# Generated by git-account-switcher. DO NOT EDIT.\n");

        for (_, account) in accounts {
            if let Some(alias) = &account.ssh_host_alias {
                s.push_str(&format!("Host {}\n", alias));
                s.push_str("    HostName github.com\n");
                s.push_str("    User git\n");
                if let Some(key) = &account.ssh_key {
                    let norm_key = normalize_path(key);
                    s.push_str(&format!("    IdentityFile {}\n", norm_key.display()));
                }
                s.push_str("    IdentitiesOnly yes\n\n");
            }
        }

        s
    }

    fn generate_shell_wrapper(&self) -> String {
        r#"# Generated by git-account-switcher. DO NOT EDIT.
gh() {
    local acc
    acc=$(git-account-switcher env --account-only 2>/dev/null)
    if [[ -n "$acc" && "$1" != "auth" ]]; then
        local token
        token=$(command gh auth token --user "$acc" 2>/dev/null)
        if [[ -n "$token" ]]; then
            GH_TOKEN="$token" command gh "$@"
            return $?
        fi
    fi
    command gh "$@"
}
"#
        .to_string()
    }
}
